name       : qt-creator
version    : 14.0.0
release    : 61
source     :
    - https://download.qt.io/official_releases/qtcreator/14.0/14.0.0/qt-creator-opensource-src-14.0.0.tar.xz : f2fdcff9cb8ed7fd5cb1fc779352c7a7a942922788ca000de85db6dbd7a8d454
homepage   : https://doc.qt.io/qtcreator/
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Help)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Quick3D)
    - pkgconfig(Qt6SerialPort)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(libdw)
    - pkgconfig(libsecret-1)
    - pkgconfig(yaml-cpp)
rundeps    :
    - qt6-base-devel
clang      : yes
environment: |
    if [[ " ${PATH[*]} " =~ "ccache" ]]; then
        export CMAKE_C_COMPILER_LAUNCHER=ccache
        export CMAKE_CXX_COMPILER_LAUNCHER=ccache
    fi
setup      : |
    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DCMAKE_INSTALL_LIBDIR=$(basename %libdir%) \
        -DPYTHON_EXECUTABLE=$(which python3) \
        -DQTC_CLANG_BUILDMODE_MATCH=ON \
        -DCLANGTOOLING_LINK_CLANG_DYLIB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
