name       : bitwarden-cli
version    : 2024.7.2
release    : 14
source     :
    - https://github.com/bitwarden/clients/archive/refs/tags/cli-v2024.7.2.tar.gz : bf86961b36784dfb04e038a295ebfdd76fe1030f215ce58da18ec9607e535fa2
homepage   : https://bitwarden.com/help/cli/
license    : GPL-3.0-only
component  : security
summary    : CLI client for Bitwarden
description: CLI client for Bitwarden, a secure and free password manager for all of your devices
networking : yes
strip      : no
debug      : no
builddeps  :
    - git
    - nodejs-18
environment: |
    export npm_config_build_from_source=true

    # npm is called recursively and we need that to use nodejs-18
    export PATH=/usr/lib64/nodejs-18/bin:$PATH
setup      : |
    npm-18 ci
build      : |
    cd apps/cli

    npm-18 run dist:oss:lin

    node-18 ./build/bw.js completion --shell zsh > _bw
install    : |
    cd apps/cli

    install -Dm00755 dist/oss/linux/bw $installdir/usr/bin/bw
    install -Dm00644 _bw $installdir/usr/share/zsh/site-functions/_bw
