name       : jabref
version    : '5.13'
release    : 5
source     :
    - https://github.com/JabRef/jabref/archive/refs/tags/v5.13.tar.gz : 35b4415acb3b8892d3d4e86d8a6f46095ba5e0f285f2daa53a19abaca0a76bca
homepage   : https://www.jabref.org/
license    : MIT
component  : office
summary    : Graphical Java application for managing BibTeX and BibLaTeX (.bib) databases
description: |
    Graphical Java application for managing BibTeX and BibLaTeX (.bib) databases
builddeps  :
    - gradle
    - openjdk-21
rundeps    :
    - openjdk-21
networking : yes
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-21
    export PATH=$JAVA_HOME/bin:$PATH

    export GRADLE_USER_HOME=$workdir
build      : |
    gradle \
      --no-daemon \
      -PprojVersionInfo=$version \
      -PprojVersion=$version \
      assemble
install    : |
    # Install java shim as binary
    install -Dm00755 $pkgfiles/jabref.sh $installdir/usr/bin/jabref
    # Install application data
    install -dm00644 $installdir/usr/share/jabref
    cp -R build/resources $installdir/usr/share/jabref
    tar -xf build/distributions/JabRef-*.tar --strip-components=1 -C $installdir/usr/share/jabref
    # Install desktop files, icons and appstream metainfo
    install -Dm00644 $pkgfiles/org.jabref.jabref.desktop -t $installdir/usr/share/applications
    install -Dm00644 build/resources/main/icons/jabref.svg $installdir/usr/share/icons/hicolor/scalable/apps/org.jabref.jabref.svg
    install -Dm00644 build/resources/main/icons/JabRef-icon-64.png $installdir/usr/share/icons/hicolor/64x64/apps/org.jabref.jabref.png
    install -Dm00644 $pkgfiles/org.jabref.jabref.png $installdir/usr/share/icons/hicolor/128x128/apps/org.jabref.jabref.png
    install -Dm00644 $pkgfiles/org.jabref.jabref.appdata.xml -t $installdir/usr/share/metainfo
