name       : cryptsetup
version    : 2.7.4
release    : 21
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/v2.7/cryptsetup-2.7.4.tar.xz : dce29903a58f7b774fe61191e7e6de955de0f40d9e27b0028ffcf3438c0e9480
homepage   : https://gitlab.com/cryptsetup/cryptsetup
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : system.base
summary    : Utility to setup disk encryption using DMCrypt
description: |
    Cryptsetup is utility used to conveniently setup disk encryption based on DMCrypt kernel module. These include plain dm-crypt volumes, LUKS volumes, loop-AES and TrueCrypt (including VeraCrypt extension) format. Project also includes veritysetup utility used to conveniently setup DMVerity block integrity checking kernel module.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(json-c)
    - pkgconfig(libgcrypt)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(popt)
    - asciidoctor
rundeps    :
    - devel : json-c-devel
optimize   :
    - size
    - lto
setup      : |
    %configure --disable-static \
               --disable-pwquality \
               --disable-rpath \
               --disable-selinux \
               --disable-ssh-token \
               --enable-udev \
               --enable-cryptsetup-reencrypt \
               --enable-largefile
build      : |
    %make
install    : |
    %make_install
