name       : breezy
version    : 3.3.4
release    : 12
source     :
    - https://launchpad.net/brz/3.3/3.3.4/+download/breezy-3.3.4.tar.gz : 7c412f39fa3c616871fb1ba2a83fca36cb65b28e7f2b55c99c663ae2d90b2301
homepage   : https://www.breezy-vcs.org/
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Breezy is a friendly powerful distributed version control system.
description: |
    Breezy is a version control system implemented in Python with multi-format support and an emphasis on hackability.
networking : yes
builddeps  :
    - pkgconfig(python3)
    - cython
    - python-build
    - python-installer
    - python-packaging
    - python-setuptools-rust
    - python-wheel
setup      : |
    # build with pep517
    rm setup.py
build      : |
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
    python3 -m pip install --user setuptools-gettext

    %python3_setup
install    : |
    %python3_install

    rm -fr $installdir/usr/lib/python%python3_version%/site-packages/breezy/tests/
replaces   :
    - bzr
