name       : lime3ds
version    : 2116
release    : 4
source     :
    - git|https://github.com/Lime3DS/Lime3DS.git : 90ebe220b200ba1d6b79a1d7fe3ef7f590c09453
homepage   : https://lime3ds.github.io/
license    : GPL-2.0-or-later
component  : games.emulator
summary    : A Nintendo 3DS emulator based on Citra
description: |
    Lime3DS is a project which aims to revive and continue work on Citra, a popular open-source Nintendo 3DS emulator which ceased development.
builddeps  :
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(RapidJSON)
    - pkgconfig(libavcodec)
    - pkgconfig(libenet)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libssl)
    - pkgconfig(libunwind)
    - pkgconfig(libusb-1.0)
    - pkgconfig(sdl2)
    - pkgconfig(soundtouch)
    - cubeb-devel
    - glslang-devel
    - libboost-devel
    - robin-map
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_QT_UPDATER=OFF \
        -DUSE_DISCORD_PRESENCE=ON \
        -DUSE_SYSTEM_BOOST=ON \
        -DUSE_SYSTEM_ENET=ON \
        -DUSE_SYSTEM_LIBUSB=ON \
        -DUSE_SYSTEM_QT=ON \
        -DUSE_SYSTEM_SDL2=ON \
        -DUSE_SYSTEM_SOUNDTOUCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/io.github.lime3ds.Lime3DS.metainfo.xml -t $installdir/usr/share/metainfo
replaces   :
    - citra
    - dbginfo : citra-dbginfo
