name       : bitwarden-desktop
version    : 2024.7.1
release    : 29
source     :
    - https://github.com/bitwarden/clients/archive/refs/tags/desktop-v2024.7.1.tar.gz : 52ecde0f9376ca49d142f40f517705ae363fd1ca5623bec52508cb1e14dbd712
license    : GPL-3.0-only
component  : security
homepage   : https://bitwarden.com/
summary    : A secure and free password manager for all of your devices
description: A secure and free password manager for all of your devices
networking : yes
builddeps  :
    - pkgconfig(cups)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pangocairo)
    - pkgconfig(xtst)
    - git
    - jq
    - nodejs
    - rust
rundeps    :
    - nodejs
setup      : |
    # export ELECTRON_VERSION=28.3.0
    # npm install electron@$ELECTRON_VERSION

    pushd apps/desktop
    tmp=$(mktemp)
    # jq ".electronVersion = \"${ELECTRON_VERSION}\"" electron-builder.json > "$tmp" && mv "$tmp" electron-builder.json

    # Create an unpacked distribution, allowing us to more easily see changes to shipped files
    jq ".linux.asar = false" electron-builder.json > "$tmp" && mv "$tmp" electron-builder.json

    # Fix appId on Wayland
    jq ".productName = \"com.bitwarden.desktop\"" electron-builder.json > "$tmp" && mv "$tmp" electron-builder.json
    jq ".linux.desktop.Name = \"com.bitwarden.desktop\"" electron-builder.json > "$tmp" && mv "$tmp" electron-builder.json

    %patch --strip=1 src/main/messaging.main.ts -i $pkgfiles/messaging.main.ts.patch
    %patch --strip=3 -i $pkgfiles/0001-Solus-Use-glibc-instead-of-musl.patch
    popd

    %patch -p1 -i $pkgfiles/fix-argon-simd.patch

    npm ci
build      : |
    export npm_config_build_from_source=true

    cd apps/desktop
    unset LD_PRELOAD
    pushd desktop_native/napi
    npm run build
    popd
    npm run build && npm run clean:dist
    npm exec -c "electron-builder --linux --x64 --dir"
install    : |
    export bwdir=/usr/share/bitwarden-desktop
    install -dm00755 $installdir/usr/bin
    install -dm00755 $installdir/$bwdir

    cp -R $workdir/apps/desktop/dist/linux-unpacked/* $installdir/$bwdir/

    mv $installdir/$bwdir/bitwarden $installdir/$bwdir/bitwarden-desktop
    install -Dm00755 $pkgfiles/bitwarden.sh $installdir/usr/bin/bitwarden-desktop

    install -Dm00644 $pkgfiles/com.bitwarden.desktop.desktop $installdir/usr/share/applications/com.bitwarden.desktop.desktop
    install -Dm00644 $pkgfiles/com.bitwarden.desktop.metainfo.xml $installdir/usr/share/metainfo/com.bitwarden.desktop.metainfo.xml

    # Fix appid since we can't seem to do this during the build
    package_json=$installdir/$bwdir/resources/app/package.json
    tmp=$(mktemp)
    jq ".productName = \"com.bitwarden.desktop\"" $package_json > "$tmp" && mv "$tmp" $package_json
    jq ".desktopName = \"com.bitwarden.desktop.desktop\"" $package_json > "$tmp" && mv "$tmp" $package_json
    chmod 644 $package_json

    for i in 16 32 64 128 256 512 1024; do
        install -Dm00644 $workdir/apps/desktop/resources/icons/${i}x${i}.png $installdir/usr/share/icons/hicolor/${i}x${i}/apps/bitwarden.png
    done
