name       : moby
version    : 27.1.1
release    : 19
source     :
    - https://github.com/moby/moby/archive/v27.1.1.tar.gz : d8afaa4513d324db5841ced641daeee9090802c765b78f1c583bc171e9b0a6fd
    - https://github.com/docker/cli/archive/refs/tags/v27.1.1.tar.gz#docker-cli.tar.gz : 84db222b6d65695f3d8ae02acf8f21d90fb3f2169754bb94d314864c37bac7f3
license    : Apache-2.0
component  : virt
homepage   : https://www.docker.com
summary    : The open-source application container engine
description: |
    The open-source application container engine. This package contains the Docker server
strip      : no
networking : yes
builddeps  :
    - pkgconfig(libsystemd)
    - git
    - go-md2man
    - golang
    - linux-headers
rundeps    :
    - containerd
    - dnsmasq
    - tini
environment: |
    export AUTO_GOPATH=1
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
    export GO111MODULE=auto
setup      : |
    mkdir docker-cli
    tar -xf $sources/docker-cli.tar.gz -C docker-cli --strip-components 1
build      : |
    export GITCOMMIT="$(git ls-remote https://github.com/moby/moby.git refs/tags/v$version^{} | awk '{print $1}')"
    export DOCKER_GITCOMMIT=$GITCOMMIT

    # Build daemon
    PLATFORM="Docker Engine - Community" \
    VERSION=${version} \
    DOCKER_BUILDTAGS="journald exclude_graphdriver_devicemapper" \
    DISABLE_WARN_OUTSIDE_CONTAINER=1 \
      ./hack/make.sh dynbinary

    # Build manpages
    cd docker-cli
    ./scripts/docs/generate-man.sh
install    : |
    # Main docker daemon
    install -Dm00755 bundles/dynbinary-daemon/dockerd $installdir/usr/bin/dockerd

    # Now install docker-init
    ln -s tini-static $installdir/usr/bin/docker-init

    # Now install proxy service
    install -Dm00755 $workdir/bundles/dynbinary-daemon/docker-proxy $installdir/usr/bin/docker-proxy

    # Now install systemd units
    install -Dm00644 $pkgfiles/docker.service -t $installdir/%libdir%/systemd/system/
    install -Dm00644 contrib/init/systemd/docker.socket -t $installdir/%libdir%/systemd/system/

    install -Dm644 $pkgfiles/docker.preset $installdir/usr/lib/systemd/system-preset/docker.preset


    # Enable socket activation by default
    install -Ddm00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../docker.socket $installdir/%libdir%/systemd/system/sockets.target.wants/docker.socket

    # Add the docker group
    install -Dm00644 $pkgfiles/docker.sysusers $installdir/%libdir%/sysusers.d/docker.conf

    # Install manpage
    install -Dm00644 docker-cli/man/man8/dockerd.8 -t $installdir/usr/share/man/man8/
