name       : python3-pycryptodome
version    : 3.20.0
release    : 18
source     :
    - https://pypi.io/packages/source/p/pycryptodome/pycryptodome-3.20.0.tar.gz : 09609209ed7de61c2b560cc5c8c4fbf892f8b15b1faf7e4cbffac97db1fffda7
homepage   : https://www.pycryptodome.org
license    :
    - BSD-2-Clause
    - MIT
component  : programming.python
summary    : Cryptographic library for Python
description: |
    PyCryptodome is a self-contained Python package of low-level cryptographic primitives.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
