name       : font-iosevka-ttf
version    : 31.0.0
release    : 71
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v31.0.0/PkgTTF-Iosevka-31.0.0.zip : fca4e8d8849b9829275bb5fac89606b8b13dcbaefa947a867e34ec2fcdc9f252
homepage   : https://typeof.net/Iosevka
license    : OFL-1.1
component  : desktop.font
summary    : Versatile typeface for code, from code.
description: |
    Iosevka is an open-source, sans-serif + slab-serif, monospace + quasi-proportional typeface family, designed for writing code, using in terminals, and preparing technical documents.
install    : |
    install -Dm00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
    install -Dm00644 $pkgfiles/iosevka.metainfo.xml $installdir/usr/share/metainfo/iosevka.metainfo.xml
