name       : libhtp
version    : 0.5.46
release    : 8
source     :
    - https://github.com/OISF/libhtp/archive/refs/tags/0.5.46.tar.gz : 31a184c9aa1d015f5add33c5480f95738189449954c383e217b27cda97e98789
license    : BSD-3-Clause
component  : security.crypto
summary    : LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
description: |
    LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
