name       : svt-av1
version    : 2.1.2
release    : 11
source     :
    - https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v2.1.2/SVT-AV1-v2.1.2.tar.bz2 : a1d95875f7539d49f7c8fdec0623fbf984804a168da6289705d53268e3b38412
license    :
    - AOMPL-1.0
    - BSD-2-Clause
component  : multimedia.codecs
homepage   : https://gitlab.com/AOMediaCodec/SVT-AV1
summary    : Scalable Video Technology for AV1 (SVT-AV1 Encoder)
description: |
    The Scalable Video Technology for AV1 (SVT-AV1 Encoder) is an AV1-compliant encoder library core.
builddeps  :
    - yasm
setup      : |
    %cmake_ninja \
        -DBUILD_APPS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
