name       : strace
version    : '6.10'
release    : 11
source     :
    - https://github.com/strace/strace/releases/download/v6.10/strace-6.10.tar.xz : 765ec71aa1de2fe37363c1e40c7b7669fc1d40c44bb5d38ba8e8cd82c4edcf07
license    : BSD-3-Clause
summary    : Diagnostic, debugging and instructional userspace utility
component  : programming.tools
description: |
    Strace is a diagnostic, debugging and instructional userspace utility for Linux. It is used to monitor and tamper with interactions between processes and the Linux kernel, which include system calls, signal deliveries, and changes of process state.
homepage   : https://strace.io/
builddeps  :
    - pkgconfig(libunwind)
clang      : yes
setup      : |
    %configure --with-libunwind
build      : |
    %make
install    : |
    %make_install
