name       : flatpak
version    : 1.14.8
release    : 78
source     :
    - https://github.com/flatpak/flatpak/releases/download/1.14.8/flatpak-1.14.8.tar.xz : 1016b7327f7af87896f95465f7e5813750d3b7049a3740a1a4ddcb5fa8c5348e
homepage   : https://flatpak.org/
license    : LGPL-2.1-or-later
component  : desktop
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(fuse3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gpgme)
    - pkgconfig(gtk-doc)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libassuan)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libseccomp)
    - pkgconfig(libzstd)
    - pkgconfig(ostree-1)
    - pkgconfig(xau)
    - bubblewrap
    - pyparsing
    - xmlto
rundeps    :
    - bubblewrap
setup      : |
    %patch -p1 -i $pkgfiles/0001-Solus-Tmpfiles-additions-for-statelessness.patch
    %configure --disable-static \
        --enable-gtk-doc \
        --with-dbus-config-dir=/usr/share/dbus-1/system.d \
        --with-privileged-group=sudo \
        --with-profile-dir=/usr/share/defaults/etc/profile.d \
        --with-system-bubblewrap \
        --with-system-helper-user=flatpak \
        --with-sysusersdir=%libdir%/sysusers.d/
build      : |
    %make
install    : |
    %make_install

    # Make sure that flatpak profile script is loaded after 10-xdg.sh
    mv $installdir/usr/share/defaults/etc/profile.d/flatpak.sh $installdir/usr/share/defaults/etc/profile.d/70-flatpak.sh

    # Add auto-update systemd services
    install -Dm00644 -t $installdir/%libdir%/systemd/system $pkgfiles/system/flatpak-update.{service,timer}
    install -Dm00644 -t $installdir/%libdir%/systemd/user $pkgfiles/user/flatpak-update.{service,timer}

    # Enable flathub
    install -dm00644 $installdir/%libdir%/systemd/system/multi-user.target.wants
    install -Dm00644 -t $installdir/%libdir%/systemd/system $pkgfiles/flatpak-enable-flathub.service
    ln -sv ../flatpak-enable-flathub.service $installdir/%libdir%/systemd/system/multi-user.target.wants/flatpak-enable-flathub.service
