name       : pcsc-tools
version    : 1.7.2
release    : 8
source     :
    - https://pcsc-tools.apdu.fr/pcsc-tools-1.7.2.tar.bz2 : fd6fcc25e8140f613b3bf44b02eda4a8a429ee4939fb777f474e2c829f7b472c
homepage   : https://pcsc-tools.apdu.fr/
license    : GPL-2.0-or-later
component  : security
summary    : Tools to be used with smart cards and PC/SC
description: |
    These tools are used to test a PC/SC driver, card or reader or send commands in a friendly environment (text or graphical user interface).
builddeps  :
    - pkgconfig(libpcsclite)
rundeps    :
    - perl-gtk3
    - perl-libintl
    - perl-pango
    - perl-pcsc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 gscriptor.desktop $installdir/usr/share/applications/gscriptor.desktop
