name       : pcsc-tools
version    : 1.7.1
release    : 7
source     :
    - https://pcsc-tools.apdu.fr/pcsc-tools-1.7.1.tar.bz2 : 0d024b589e15d79eac8506cd67df7b53cf91e9e6a493c8319f33cd29b5f36426
license    : GPL-2.0-or-later
component  : security
homepage   : https://pcsc-tools.apdu.fr/
summary    : Tools to be used with smart cards and PC/SC
description: |
    These tools are used to test a PC/SC driver, card or reader
    or send commands in a friendly environment (text or graphical user interface).
builddeps  :
    - pkgconfig(libpcsclite)
rundeps    :
    - perl-gtk3
    - perl-pango
    - perl-pcsc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 gscriptor.desktop $installdir/usr/share/applications/gscriptor.desktop

