name       : python-packaging
version    : '22.0'
release    : 21
source     :
    - https://pypi.io/packages/source/p/packaging/packaging-22.0.tar.gz : 2198ec20bd4c017b8f9717e00f0c8714076fc2fd93816750ab48e2c41de2cfd3
homepage   : https://github.com/pypa/packaging
license    : Apache-2.0
component  : programming.python
summary    : Core utilities for Python packages
description: |
    Reusable core utilities for various Python Packaging interoperability specifications. This library provides utilities that implement the interoperability specifications which have clearly one correct behaviour (eg: PEP 440) or benefit greatly from having a single shared implementation (eg: PEP 425).
networking : no # flip this for python3 rebuilds
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
checkdeps  :
    - python-pretend
    - python-pytest
environment: |
    # flip this for python3 rebuilds
    export BOOTSTRAP=0
build      : |
    if [[ ${BOOTSTRAP} == "1" ]]; then
        python3 -m pip wheel --no-deps .
    else
        %python3_setup
    fi
install    : |
    if [[ ${BOOTSTRAP} == "1" ]]; then
        python3 -m pip install --root=%installroot% --no-deps --ignore-installed .
    else
        %python3_install
    fi
check      : |
    if [[ ${BOOTSTRAP} != "1" ]]; then
        %python3_test py.test3 -v
    fi
