name       : fastfetch
version    : 2.21.3
release    : 29
source     :
    - https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.21.3.tar.gz : cec1f126ade7a5ef971901b1cdbe79f5864523d7a0a92732991619485d13e2e7
homepage   : https://github.com/fastfetch-cli/fastfetch
license    : MIT
component  : system.utils
summary    : Like neofetch, but much faster because written in C
description: |
    Fastfetch is a neofetch-like tool for fetching system information and displaying them in a pretty way. It is written in pure c, with performance and customizability in mind.
builddeps  :
    - pkgconfig(elfutils)
    - pkgconfig(ImageMagick)
    - pkgconfig(OpenCL)
    - pkgconfig(dbus)
    - pkgconfig(dconf)
    - pkgconfig(gio-2.0)
    - pkgconfig(libdrm)
    - pkgconfig(libxfconf-0)
    - pkgconfig(osmesa)
    - pkgconfig(sqlite3)
    - pkgconfig(vulkan)
    - pkgconfig(wayland)
    - pkgconfig(xrandr)
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DENABLE_IMAGEMAGICK6='OFF' \
        -DENABLE_RPM='OFF' \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/licenses
