name       : ppp
version    : 2.5.0
release    : 12
source     :
    - https://download.samba.org/pub/ppp/ppp-2.5.0.tar.gz : 5cae0e8075f8a1755f16ca290eb44e6b3545d3f292af4da65ecffe897de636ff
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : network.util
homepage   : https://ppp.samba.org
summary    : an open source package which implements the Point-to-Point Protocol (PPP) on Linux and Solaris systems
description: |
    an open source package which implements the Point-to-Point Protocol (PPP) on Linux and Solaris systems
builddeps  :
    - pkgconfig(libpcap)
    - pkgconfig(libxcrypt)
setup      : |
    %apply_patches

    %configure --enable-systemd
build      : |
    %make
install    : |
    %make_install

    # Create the directory for the lock files
    install -Dm00644 $pkgfiles/ppp.tmpfiles $installdir/%libdir%/tmpfiles.d/ppp.conf

    # Statelesss
    install -dm00755 $installdir/usr/share/defaults/ppp

    # These are the only two config files we need to keep
    mv -v $installdir/etc/ppp/{openssl.cnf,options} $installdir/usr/share/defaults/ppp
    # These are just comments and being empty is not an error
    rm -v $installdir/etc/ppp/{chap-secrets,eaptls-client,eaptls-server,pap-secrets}

    rmdir -v $installdir/etc/ppp \
             $installdir/etc
