name       : re2
version    : 2023.11.01
release    : 10
source     :
    - https://github.com/google/re2/archive/refs/tags/2023-11-01.tar.gz : 4e6593ac3c71de1c0f322735bc8b0492a72f66ffccfad76e259fa21c41d27d8a
license    : BSD-3-Clause
component  : programming.library
summary    : RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines
description: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library.
libsplit   : no
builddeps  :
    - pkgconfig(absl_config)
    - pkgconfig(icu-uc)
checkdeps  :
    - pkgconfig(gtest)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON \
                 -DRE2_USE_ICU=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %make test
