name       : fmt
version    : 10.1.1
release    : 8
source     :
    - https://github.com/fmtlib/fmt/releases/download/10.1.1/fmt-10.1.1.zip : b84e58a310c9b50196cda48d5678d5fa0849bca19e5fdba6b684f0ee93ed9d1b
license    : BSD-2-Clause
component  : programming.library
homepage   : https://fmt.dev/
summary    : Small, safe and fast formatting C++ library
description: |
    {fmt} is an open-source formatting library for C++. It can be used as a safe and fast alternative to (s)printf and IOStreams.
clang      : yes
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
