name       : rizin
version    : 0.7.0
release    : 33
source     :
    - https://github.com/rizinorg/rizin/releases/download/v0.7.0/rizin-src-v0.7.0.tar.xz : fc6734320d88b9e2537296aa0364a3c3b955fecc8d64dda26f1f3ede7c8d6c31
license    : LGPL-3.0-or-later
component  : programming.tools
homepage   : https://rizin.re/
summary    : UNIX-like reverse engineering framework and command-line toolset
description: |
    A free and open-source Reverse Engineering framework, providing a complete binary analysis experience with features like Disassembler, Hexadecimal editor, Emulation, Binary inspection, Debugger, and more.
replaces   :
    - radare2
    - devel :
        - radare2-devel
builddeps  :
    - pkgconfig(capstone)
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
    - pkgconfig(libmspack)
    - pkgconfig(libpcre2-8)
    - pkgconfig(libxxhash)
    - pkgconfig(libzip)
    - pkgconfig(libzstd)
    - pkgconfig(tree-sitter)
setup      : |
    %meson_configure \
        -Dchecks_level=1 \
        -Denable_rz_test=false \
        -Denable_tests=false \
        -Dpackager=Solus \
        -Dpackager_version=$version-$release \
        -Duse_sys_capstone=enabled \
        -Duse_sys_libmspack=enabled \
        -Duse_sys_libzip=enabled \
        -Duse_sys_libzstd=enabled \
        -Duse_sys_lz4=enabled \
        -Duse_sys_lzma=enabled \
        -Duse_sys_magic=enabled \
        -Duse_sys_openssl=enabled \
        -Duse_sys_pcre2=enabled \
        -Duse_sys_tree_sitter=enabled \
        -Duse_sys_xxhash=enabled \
        -Duse_sys_zlib=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
