name       : phonon
version    : 4.12.0
release    : 20
source     :
    - https://download.kde.org/stable/phonon/4.12.0/phonon-4.12.0.tar.xz : 3287ffe0fbcc2d4aa1363f9e15747302d0b080090fe76e5f211d809ecb43f39a
homepage   : https://invent.kde.org/libraries/phonon
license    : LGPL-2.1-only
component  : desktop.multimedia
summary    : Qt-style interface for audio and video.
description: |
    Qt-style interface for audio and video.
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Designer)
    - extra-cmake-modules
rundeps    :
    - alsa-plugins
    - phonon-backend-gstreamer
    - qt5 :
        - phonon-common
    - qt6 :
        - phonon-common
setup      : |
    mkdir qt5 qt6
    pushd qt5
    %cmake_ninja -DPHONON_BUILD_PHONON4QT5=TRUE -DPHONON_BUILD_PHONON4QT6=FALSE .. ..
    popd

    pushd qt6
    %cmake_ninja -DPHONON_BUILD_PHONON4QT6=TRUE -DPHONON_BUILD_PHONON4QT5=FALSE .. ..
    popd
build      : |
    pushd qt5
    %ninja_build
    popd

    pushd qt6
    %ninja_build
    popd
install    : |
    pushd qt5
    %ninja_install
    popd

    pushd qt6
    %ninja_install
    popd
patterns   :
    - common :
        - /usr/bin/phononsettings
        - /usr/share/locale/*
    - qt5 :
        - /usr/lib64/libphonon4qt5*.so.*
        - /usr/lib64/qt5/plugins/designer/phonon4qt5widgets.so
    - qt6 :
        - /usr/lib64/libphonon4qt6*.so.*
        - /usr/lib64/qt6/plugins/designer/phonon4qt6widgets.so
    - qt5-devel :
        - /usr/include/phonon4qt5
        - /usr/lib64/cmake/phonon4qt5
        - /usr/lib64/libphonon4qt5*.so
        - /usr/lib64/pkgconfig/phonon4qt5.pc
        - /usr/lib64/qt5/mkspecs/modules/qt_phonon4qt5.pri
    - qt6-devel :
        - /usr/include/phonon4qt6
        - /usr/lib64/cmake/phonon4qt6
        - /usr/lib64/libphonon4qt6*.so
        - /usr/lib64/pkgconfig/phonon4qt6.pc
replaces   :
    - qt5 : phonon
    - qt5-devel : phonon-devel
