name       : ncurses
version    : 6.5.20240727
release    : 28
source     :
    # They seem to prune these from time to time. Might be smarter to host the archives ourselves
    - https://invisible-island.net/archives/ncurses/current/ncurses-6.5-20240727.tgz : c6b3ead29934547596753519256c024cca798b8b838289912dca10a92a23ec91
homepage   : http://www.gnu.org/software/ncurses
license    : GPL-3.0-or-later
component  : system.base
summary    : The ncurses library routines are a terminal-independent method of updating character screens with reasonable optimization.
description: |
    The ncurses library routines are a terminal-independent method of updating character screens with reasonable optimization. This package contains the shared libraries necessary to run programs compiled with ncurses.
devel      : true
autodep    : no
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
optimize   :
    - speed
    - lto
environment: |
    export CFLAGS="$CFLAGS -ffat-lto-objects"
    export CXXFLAGS="$CXXFLAGS -ffat-lto-objects"
setup      : |
    %patch -p1 -i $pkgfiles/pkgconfig.patch

    %configure --libdir=%libdir% \
               --with-cxx-binding \
               --with-cxx-shared \
               --with-manpage-format=gzip \
               --with-pkg-config-libdir=%libdir%/pkgconfig \
               --with-shared \
               --with-rcs-ids \
               --with-terminfo-dirs='/usr/share/terminfo:/etc/terminfo' \
               --with-versioned-syms \
               --without-ada \
               --without-debug \
               --enable-colorfgbg \
               --enable-hard-tabs \
               --enable-largefile \
               --enable-pc-files \
               --enable-xmc-glitch \
               --enable-widec \
               --disable-rpath \
               --disable-root-access \
               --disable-root-environ \
               --disable-setuid-environ
build      : |
    %make
install    : |
    %make_install

    # wide vs non-wide, we'll demote non-wide at some point
    if [[ -z "${EMUL32BUILD}" ]]; then
        for i in ncurses ncursesw ; do
            install -d $installdir/usr/include/${i}
            for j in $installdir/usr/include/*.h ; do
                ln -sv ../$(basename ${j}) $installdir/usr/include/${i}/$(basename ${j})
            done
        done

        # Make these guys visible to musl
        install -D -d -m 00755 $installdir/usr/include/musl
        for i in $installdir/usr/include/*.h ; do
            ln -sv ../$(basename $i) $installdir/usr/include/musl/.
        done
    fi

    # link nonwide..
    for f in $installdir/%libdir%/*w.* ; do
        src=$(basename ${f})
        dst=`echo "$src" | sed 's@w\.@.@g'`
        ln -sv "$src" $installdir/%libdir%/${dst}
    done

    # last compat symlinks
    ln -sv libncurses.so $installdir/%libdir%/libcurses.so
    ln -sv libncurses.a $installdir/%libdir%/libcurses.a
    ln -sv libncursesw.so $installdir/%libdir%/libcursesw.so
    ln -sv libncursesw.a $installdir/%libdir%/libcursesw.a

    ln -sv libncurses.so.6 $installdir/%libdir%/libtinfo.so.6
