name       : libwpe
version    : 1.16.0
release    : 11
source     :
    - https://github.com/WebPlatformForEmbedded/libwpe/releases/download/1.16.0/libwpe-1.16.0.tar.xz : c7f3a3c6b3d006790d486dc7cceda2b6d2e329de07f33bc47dfc53f00f334b2a
homepage   : https://github.com/WebPlatformForEmbedded/libwpe
license    : BSD-2-Clause
component  : programming.library
summary    : General-purpose library specifically developed for the WPE-flavored port of WebKit.
description: |
    General-purpose library specifically developed for the WPE-flavored port of WebKit.
builddeps  :
   - pkgconfig(gbm)
   - pkgconfig(xkbcommon)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
