name       : python-cachetools
version    : 5.4.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/c/cachetools/cachetools-5.4.0.tar.gz : b8adc2e7c07f105ced7bc56dbb6dfbe7c4a00acce20e2227b3f355be89bc6827
homepage   : https://github.com/tkem/cachetools/
license    : MIT
component  : programming.python
summary    : Extensible memoizing collections and decorators
description: |
    This module provides various memoizing collections and decorators, including variants of the Python 3 Standard Library @lru_cache function decorator.
rundeps    :
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
