name       : plasma-nm
version    : 6.0.4
release    : 102
source     :
    - https://download.kde.org/stable/plasma/6.0.4/plasma-nm-6.0.4.tar.xz : 64519d9d05fcb4f85c7b9c4708cc6f510e28fdc272b6d0e2a7a1efc03888c6df
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
libsplit   : no
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(mobile-broadband-provider-info)
    - pkgconfig(openconnect)
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-ksvg-devel
    - kf6-kwallet-devel
    - kf6-modemmanager-qt-devel
    - kf6-networkmanager-qt-devel
    - kf6-prison-devel
    - libplasma-devel
    - qca-qt6-devel
    - qcoro-qt6-devel
rundeps    :
    - kf6-kirigami
    - kf6-prison
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
