name       : git-cola
version    : 4.8.1
release    : 36
source     :
    - https://github.com/git-cola/git-cola/archive/refs/tags/v4.8.1.tar.gz : a9c175e64bdf86cce4160365dc9365d6ecab9a76e005baa747712b4de9f57867
homepage   : https://git-cola.github.io
license    : GPL-2.0-or-later
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    git-cola is a powerful Git GUI with a slick and intuitive user interface.
networking : yes
builddeps  :
    - pkgconfig(python3)
    - git
    - python-qtpy
    - python3-qt5
rundeps    :
    - git
    - meld
    - python-polib
    - python-qtpy
    - python3-qt5
build      : |
    %make
install    : |
    %make_install prefix=/usr PIP=pip3

    # No, you will not handle every single folder I want to open.
    rm $installdir/usr/share/applications/git-cola-folder-handler.desktop
