name       : thin-provisioning-tools
version    : 1.0.14
release    : 11
source     :
    - https://github.com/jthornber/thin-provisioning-tools/archive/refs/tags/v1.0.14.tar.gz : 5abe8a23b077596dc9134396aa4bd0a288bf6fd63d455715d5a41a325b3ec2e6
license    : GPL-3.0-or-later
component  : system.utils
homepage   : https://github.com/jthornber/thin-provisioning-tools
summary    : A suite of tools for manipulating the metadata of the dm-thin, dm-cache and dm-era device-mapper targets
description: |
    A suite of tools for manipulating the metadata of the dm-thin, dm-cache and dm-era device-mapper targets.
networking : yes
builddeps  :
    - pkgconfig(devmapper)
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %make_install
