name       : cargo-c
version    : 0.10.3
release    : 34
source     :
    - https://github.com/lu-zero/cargo-c/archive/refs/tags/v0.10.3.tar.gz : 922171afb3ceaf6553ff3916ae4663d3743ba22f80725f2300a26b76eb6eb94f
    - https://github.com/lu-zero/cargo-c/releases/download/v0.10.3/Cargo.lock : 6c099fe28666e4c6b5da41b65d00de35c9c60ab336c625d845f28055a0e90a7d
license    : MIT
component  : programming.tools
homepage   : https://crates.io/crates/cargo-c
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libssh2)
    - pkgconfig(sqlite3)
    - rust
rundeps    :
    - rust
networking : yes
environment: |
    # Force libsqlite3-sys and libssh2-sys to use the system deps
    export LIBSQLITE3_SYS_USE_PKG_CONFIG=1
    export LIBSSH2_SYS_USE_PKG_CONFIG=1
setup      : |
    cp $sources/Cargo.lock ./Cargo.lock
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    for p in api build install test; do
    %cargo_install cargo-c${p}
    done
