name       : xdg-desktop-portal-xapp
version    : 1.0.8
release    : 4
source     :
    - https://github.com/linuxmint/xdg-desktop-portal-xapp/archive/refs/tags/1.0.8.tar.gz : 7cbb9f55d52ba707bb4ce5558e1277eb65da8c12d3e926247b04dff2bf7264db
license    : LGPL-2.1-or-later
component  : desktop.util
homepage   : https://github.com/linuxmint/xdg-desktop-portal-xapp
summary    : xdg-desktop-portal backend for MATE and XFCE
description: |
    xdg-desktop-portal backend for MATE and XFCE
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xdg-desktop-portal)
rundeps    :
    - xapp
    - xdg-desktop-portal
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
