name       : codespell
version    : 2.3.0
release    : 3
source     :
    - https://pypi.debian.net/codespell/codespell-2.3.0.tar.gz : 360c7d10f75e65f67bad720af7007e1060a5d395670ec11a7ed1fed9dd17471f
homepage   : https://github.com/codespell-project/codespell
license    : GPL-2.0-only
component  : programming.python
summary    : Fix common misspellings in source code
description: |
    Fix common misspellings in text files. It's designed primarily for checking misspelled words in source code, but it can be used with other files as well
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools-scm
setup      : |
    %python3_setup
install    : |
    %python3_install
