name       : pcsc-lite
version    : 2.2.3
release    : 17
source     :
    - https://github.com/LudovicRousseau/PCSC/archive/refs/tags/2.2.3.tar.gz : 6e0205a47ec0dd10c000965ee88e08e60c2f7f3ce7280ce0e624915821ea2402
homepage   : https://pcsclite.apdu.fr/
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    Middleware to access a smart card using SCard API (PC/SC)
builddeps  :
    - doxygen
clang      : yes
optimize   : thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-solus-Restore-library-version.patch

    %meson_configure \
                     -Dsystemdunit=system \
                     -Dusbdropdir=%libdir%/pcsc/drivers
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Enable the socket by default
    install -dm00755 $installdir/usr/lib/systemd/system/sockets.target.wants
    ln -sv ../pcscd.socket -t $installdir/usr/lib/systemd/system/sockets.target.wants
