name       : libxkbcommon
version    : 1.7.0
release    : 14
source     :
    - https://github.com/xkbcommon/libxkbcommon/archive/refs/tags/xkbcommon-1.7.0.tar.gz : 20d5e40dabd927f7a7f4342bebb1e8c7a59241283c978b800ae3bf60394eabc4
license    : MIT
component  : desktop.library
homepage   : https://xkbcommon.org
summary    : xkbcommon is a library to handle keyboard description
description: |
    xkbcommon is a library to handle keyboard descriptions, including loading them from disk, parsing them and handling their state. It's mainly meant for client toolkits, window systems, and other system applications; currently that includes Wayland, kmscon, GTK+, Qt, Clutter, and more. Despite the name, it isn't actually used by anything X11 (yet).
emul32     : yes
builddeps  :
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(wayland-client)
    - pkgconfig32(xcb-xkb)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-macros)
rundeps    :
    - xkeyboard-config
checkdeps  :
    - xorg-server-xvfb
setup      : |
    %meson_configure -Denable-docs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
