name       : usysconf-epoch
version    : 0.0.1
release    : 8
source     :
    # We need something for a source
    - https://getsol.us/sources/hotspot.txt : a12b7cb43c9d9134b5bb1b35e9096b66775d9e92e7611d1cc92b02edd6782a87
extract    : no
homepage   : https://github.com/getsolus/usysconf/
license    : GPL-2.0-only
component  : system.base
summary    : Temporary package for hosting the epoch script
description: |
    Temporary package for hosting the epoch script
install    : |
    install -Dm00755 $pkgfiles/epoch.sh -t $installdir/usr/lib64/usysconf/

    # Systemd units to run this early in the boot
    install -Dm00644 $pkgfiles/usysconf-epoch.service -t $installdir/%libdir%/systemd/system/

    install -Ddm00755 $installdir/%libdir%/systemd/system/sysinit.target.wants
    ln -srv $installdir/%libdir%/systemd/system/usysconf-epoch.service $installdir/%libdir%/systemd/system/sysinit.target.wants/usysconf-epoch.service
