name       : goverlay
version    : 1.2.0
release    : 17
source     :
    - https://github.com/benjamimgois/goverlay/archive/refs/tags/1.2.tar.gz : ce18c2a0810f6dc5f4e27f35d5f8d8353ef3bc78e36de57eaeb50a0821691c24
homepage   : https://github.com/benjamimgois/goverlay
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud, vkBasalt and ReplaySorcery
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
    It also serves as an alternative to Nvidia Shadowplay, alowing you to record gameplay as well as save replays instantly with ReplaySorcery.
builddeps  :
    - pkgconfig(x11)
    - lazarus
    - qt6pas-devel
rundeps    :
    - git
    - mangohud
    - mesa-demos
    - replaysorcery
    - vkbasalt
    - vulkan-tools
build      : |
    lazbuild --lazarusdir=%libdir%/lazarus --bm=Release goverlay.lpi
install    : |
    %make_install prefix=/usr
