---
freeze:
  start: null
  end: null

# Configuration for including static libraries.
static_libs:
  # These packages are allowed to include static libraries:
  allowed_packages:
    - gcc
    - ghc
    - glibc
    - golang
    - libboost
    - llvm
    - llvm-15
    - rocm-llvm
  # These files are allowed as static libraries:
  allowed_files:
    - /usr/lib64/ghc-*/**
