name       : xfce4-screenshooter
version    : 1.11.1
release    : 4
source     :
    - https://archive.xfce.org/src/apps/xfce4-screenshooter/1.11/xfce4-screenshooter-1.11.1.tar.bz2 : d94c4a37ac9b26f6d73214bdc254624a4ede4e111bee8d34e689f8f04c37d34d
homepage   : https://docs.xfce.org/apps/screenshooter/start
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : An application to take screenshots for xfce.
description: |
    An application to take screenshots for xfce.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(libxfce4panel-2.0)
    - pkgconfig(libxfce4ui-2)
setup      : |
    %configure --disable-debug
build      : |
    %make
install    : |
    %make_install
