name       : gtest
version    : 1.15.0
release    : 9
source     :
    - https://github.com/google/googletest/archive/refs/tags/v1.15.0.tar.gz : 7315acb6bf10e99f332c8a43f00d5fbb1ee6ca48c52f6b936991b216c586aaad
homepage   : https://google.github.io/googletest/
license    : BSD-3-Clause
libsplit   : no
component  : programming.tools
summary    : Google's C++ test framework
description: |
    GoogleTest is Google’s C++ testing and mocking framework.
setup      : |
    sed -i 's/DESTINATION lib/DESTINATION lib64/' google{mock,test}/CMakeLists.txt

    # Set the version correctly
    sed -e "s/set(GOOGLETEST_VERSION .*)/set(GOOGLETEST_VERSION %version%)/" -i CMakeLists.txt

    %cmake_ninja \
                 -DBUILD_SHARED_LIBS=ON \
                 -Dgtest_build_tests=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
patterns   :
    - /*
