name       : yt-dlp
version    : 2024.08.01
release    : 224
source     :
    - https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2024.08.01.tar.gz : d4a183d8c3f7579eacf15b959a4203f987faacf3a60284a6c6b78a50eb0051ba
license    : Unlicense
component  : network.download
homepage   : https://github.com/yt-dlp/yt-dlp
summary    : yt-dlp is a small command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlp, a fork of youtube-dl, is a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
    - yt-dlc
builddeps  :
    - pkgconfig(python3)
    - pandoc
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - mutagen
    - python-certifi
    - python-websockets
    - python3
    - python3-pycryptodome
build      : |
    %make PREFIX=$installdir/usr yt-dlp.1 completion-bash completion-fish completion-zsh
    python3 -m build --wheel --no-isolation
install    : |
    python3 -m installer --destdir="$installdir" dist/*.whl
    rm -rf $installdir/usr/share/doc
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/youtube-dl
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/yt-dlc
