name       : libolm
version    : 3.2.15
release    : 3
source     :
    - https://gitlab.matrix.org/matrix-org/olm/-/archive/3.2.15/olm-3.2.15.tar.gz : 0c63362b8be78580c2ff862297386ceb00fb05b295ce346f6fff8be8ac49eded
license    : Apache-2.0
homepage   : https://gitlab.matrix.org/matrix-org/olm
component  : security.library
summary    : Implementation of the Olm and Megolm cryptographic ratchets
description: |
    Implementation of the Olm and Megolm cryptographic ratchets
builddeps  :
    - pkgconfig(libsodium)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    cd solusBuildDir/tests
    ctest
