name       : bottom
version    : 0.10.1
release    : 24
source     :
    - https://github.com/ClementTsang/bottom/archive/refs/tags/0.10.1.tar.gz : c0e507cc3a5246e65521e91391410efc605840abe3b40194c5769265051fa1cc
    - https://github.com/ClementTsang/bottom/releases/download/0.10.1/completion.tar.gz : 87a722518bbed7012214ff77425aa69b582c8ab1d50817f427b1c920da420710
    - https://github.com/ClementTsang/bottom/releases/download/0.10.1/manpage.tar.gz : a320f028f728fbdbdea1d309840544a1da15243f158477a537bb8eeab05259f7
homepage   : https://clementtsang.github.io/bottom
license    : MIT
component  : system.utils
summary    : Yet another cross-platform graphical process/system monitor.
description: |
    A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
networking : yes
builddeps  :
    - rust
setup      : |
    %cargo_fetch
    cp $sources/completion.tar.gz .
    cp $sources/manpage.tar.gz .

    tar xf completion.tar.gz
    tar xf manpage.tar.gz
build      : |
    %cargo_build --bin btm
install    : |
    %cargo_install btm

    # Completions
    install -Dm00644 btm.bash $installdir/usr/share/bash-completion/completions/btm
    install -Dm00644 _btm $installdir/usr/share/zsh/site-functions/_btm
    install -Dm00644 btm.fish $installdir/usr/share/fish/vendor_completions.d/btm.fish

    # Manpages
    install -Dm00644 btm.1.gz $installdir/usr/share/man/man1/btm.1.gz
