name       : kf6-knotifyconfig
version    : 5.248.0
release    : 1
source     :
    - https://download.kde.org/unstable/frameworks/5.248.0/knotifyconfig-5.248.0.tar.xz : dc0032a3726039cec039b44efed774c776b7a5223673f2f3eaaf80c720952862
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-only
component  :  desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
builddeps  :
    - pkgconfig(libcanberra)
    - kf6-kio-devel
    - kf6-knotifications-devel
rundeps    :
    - devel :
        - kf6-knotifications-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
