name       : btrfs-progs
version    : '6.10'
release    : 66
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.10.tar.xz : 3382a84e3fcfe1ffdea07a61ab3f4e86665d38fa35f1f34548d5df867423e0df
license    : GPL-2.0-only
homepage   : https://btrfs.wiki.kernel.org/index.php/Main_Page
summary    :
    - Utilities for managing btrfs filesystems
    - libbtrfs : Library for managing btrfs filesystems
component  :
    - system.utils
    - libbtrfs : system.base
description:
    - Utilities for managing btrfs filesystems
    - libbtrfs : Library for managing btrfs filesystems
patterns   :
    - libbtrfs :
        - /usr/lib64/libbtrfs.so.*
        - /usr/lib64/libbtrfsutil.so.*
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libeconf)
    - pkgconfig(libzstd)
    - pkgconfig(lzo2)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - python-sphinx
    - python-sphinx-rtd-theme
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
