name       : gst-python
version    : 1.24.6
release    : 34
source     :
    - https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.24.6.tar.xz : 692e88820e097b30e5f92d37d0955c709a0a17b27f874a1907405244825bd700
license    : LGPL-2.1-or-later
homepage   : https://gstreamer.freedesktop.org/
summary    : GStreamer Python Bindings Supplement
component  : programming.python
description: |
    GStreamer python overrides for the gobject-introspection-based pygst bindings.
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
rundeps    :
    - gstreamer-1.0-plugins-base
environment: |
    export PYTHON=/usr/bin/python3
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
check      : |
    %ninja_check || :
