name       : bcc
version    : 0.31.0
release    : 3
source     :
    - https://github.com/iovisor/bcc/releases/download/v0.31.0/bcc-src-with-submodule.tar.gz : 539a9e937b42f79ec525a05daa1b2a4ce0bf444fc692e2ac21e618f91605e089
homepage   : https://github.com/iovisor/bcc
license    : Apache-2.0
component  : system.utils
summary    : BPF Compiler Collection
description: |
    BPF Compiler Collection
builddeps  :
    - pkgconfig(libbpf)
    - pkgconfig(libelf)
    - linux-tools
clang      : yes
optimize   : thin-lto
setup      : |
    %cmake_ninja \
                -DCMAKE_USE_LIBBPF_PACKAGE=ON \
                -DENABLE_LLVM_SHARED=1 \
                -DENABLE_TESTS=OFF \
                -DPYTHON_CMD=python3 \
                -DREVISION=$version \
                -DRUN_LUA_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Make symlinks for all tools available with bpf- prefix
    install -dm00755 $installdir/usr/sbin
    pushd $installdir/usr/share/bcc/tools
    for f in *; do
        if [ ! -d "$f" ]; then
            ln -srv $installdir/usr/share/bcc/tools/$f $installdir/usr/sbin/bpf-$f
        fi
    done
    popd

    # Fix manpages
    mv $installdir/usr/share/bcc/man $installdir/usr/share/man
    pushd $installdir/usr/share/man/man8
    for i in *; do
        mv $i bcc-$i
    done
    popd

    # Fix shebangs
    find $installdir/usr/share/bcc/{tools,examples} -type f -exec \
        sed -i -e '1s=^#!/usr/bin/python\([0-9.]\+\)\?$=#!/usr/bin/python3=' \
            -e '1s=^#!/usr/bin/env python\([0-9.]\+\)\?$=#!/usr/bin/env python3=' \
            -e '1s=^#!/usr/bin/env bcc-lua$=#!/usr/bin/bcc-lua=' {} \;
    %python3_compile

    # Cleanup static
    rm $installdir/usr/lib64/*.a
patterns   :
    - docs :
        - /usr/share/bcc/examples
        - /usr/share/bcc/tools/doc
