name       : libzip
version    : 1.10.1
release    : 19
source     :
    - https://libzip.org/download/libzip-1.10.1.tar.xz : dc3c8d5b4c8bbd09626864f6bcf93de701540f761d76b85d7c7d710f4bd90318
homepage   : https://libzip.org/
license    : BSD-3-Clause
component  : programming.library
summary    : libzip is a C library for reading, creating, and modifying zip archives
description: |
    libzip is a C library for reading, creating, and modifying zip archives.
mancompress: yes
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(libcrypto)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
setup      : |
    %cmake_ninja -DBUILD_REGRESS=OFF \
                 -DDOCUMENTATION_FORMAT=man \
                 -DENABLE_GNUTLS=OFF \
                 -DENABLE_MBEDTLS=OFF \
                 -DENABLE_OPENSSL=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
# TODO package nihtest so that we can run the testsuite (needs -DBUILD_REGRESS=ON)
# check      : |
#     %ninja_check
