name       : thunar
version    : 4.18.11
release    : 7
source     :
    - https://archive.xfce.org/src/xfce/thunar/4.18/thunar-4.18.11.tar.bz2 : 7d0bdae2076a568c137d403ab5600e06a7a4f7a02514d486da7b8414aa75d612
homepage   : https://docs.xfce.org/xfce/thunar/start
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Modern, fast and easy-to-use file manager for Xfce.
description: |
    Modern, fast and easy-to-use file manager for Xfce.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(libxfce4ui-2)
rundeps    :
    - gvfs
setup      : |
    %configure \
        --disable-debug \
        --enable-gio-unix \
        --enable-gudev \
        --enable-notifications \
        --enable-exif \
        --sysconfdir=/usr/share

build      : |
    %make
install    : |
    %make_install

    # Rename to fix appdata stream generation
    mv $installdir/usr/share/applications/{thunar,org.xfce.Thunar}.desktop
