name       : libtirpc
version    : 1.3.5
release    : 15
source     :
    - https://sourceforge.net/projects/libtirpc/files/libtirpc/1.3.5/libtirpc-1.3.5.tar.bz2 : 9b31370e5a38d3391bf37edfa22498e28fe2142467ae6be7a17c9068ec0bf12f
homepage   : https://sourceforge.net/projects/libtirpc/
license    : BSD-3-Clause
component  : programming.library
summary    : Transport Independent RPC library (SunRPC replacement)
description: |
    The libtirpc package contains libraries that support programs that use the Remote Procedure Call (RPC) API. It replaces the RPC, but not the NIS library entries that used to be in glibc.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(krb5)
setup      : |
    %patch -p1 -i $pkgfiles/0001-Use-vendor-config-files-as-fallback-for-a-stateless-.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 doc/netconfig $installdir/usr/share/defaults/etc/netconfig
    rm -rvf $installdir/etc
