name       : eza
version    : 0.18.24
release    : 28
source     :
    - https://github.com/eza-community/eza/archive/refs/tags/v0.18.24.tar.gz : bdcf83f73f6d5088f6dc17c119d0d288fed4acd122466404772be5ef278887de
homepage   : https://github.com/eza-community/eza
license    : MIT
component  : system.utils
summary    : A modern, maintained replacement for ls
description: |
    eza is a modern, maintained replacement for the venerable file-listing command-line program ls that ships with Unix and Linux operating systems, giving it more features and better defaults. It uses colours to distinguish file types and metadata. It knows about symlinks, extended attributes, and Git. And it’s small, fast, and just one single binary.
networking : yes
replaces   :
    - exa
builddeps  :
    - pkgconfig(libgit2)
    - pandoc
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build

    # Compile the man pages
    mkdir -p target/release/man

    for manpage in eza.1 eza_colors.5 eza_colors-explanation.5; do
        pandoc --standalone -f markdown -t man "man/${manpage}.md" > "target/release/man/${manpage}"
    done
install    : |
    %cargo_install

    install -Dm00644 completions/bash/eza -t $installdir/usr/share/bash-completion/completions
    install -Dm00644 completions/zsh/_eza -t $installdir/usr/share/zsh/site-functions
    install -Dm00644 completions/fish/eza.fish -t $installdir/usr/share/fish/vendor_completions.d

    install -Dm00644 target/release/man/eza.1 $installdir/usr/share/man/man1/eza.1
    install -Dm00644 -t $installdir/usr/share/man/man5/ target/release/man/eza*.5
check      : |
    %cargo_test
