name       : gstreamer-1.0-libav
version    : 1.24.6
release    : 40
source     :
    - https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.24.6.tar.xz : 4bbd08481a390f907e342aa3f25ab885c80ec0a53f3b14244cf733cc8622f2bf
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
homepage   : https://gstreamer.freedesktop.org/
summary    : GStreamer libav based plugin
description: |
    GStreamer libav based plugin providing H264, AVI support, amongst others
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libavcodec)
setup      : |
    %meson_configure -D package-name="GStreamer Libav Plugins ${version} Solus" \
        -D package-origin="https://getsol.us" 
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
