name       : diffoscope
version    : '273'
release    : 8
source     :
    - https://diffoscope.org/archive/diffoscope-273.tar.bz2 : 4dc711fd5c6ae997fdb44be49cb59ec0f56f26aa3ca554888b5f8ac4a3004aae
homepage   : https://diffoscope.org/
license    : GPL-3.0-or-later
component  : programming.python
summary    : In-depth comparison of files, archives, and directories
description: |
    diffoscope tries to get to the bottom of what makes files or directories different. It will recursively unpack archives of many kinds and transform various binary formats into more human-readable form to compare them. It can compare two tarballs, ISO images, or PDF just as easily.
builddeps  :
    - help2man
    - python-build
    - python-docutils
    - python-installer
    - python-libarchive-c
    - python-packaging
    - python-wheel
rundeps    :
    - binutils
    - bzip2
    - cpio
    - diffutils
    - dtc
    - gettext
    - gzip
    - libxmlb
    - llvm
    - lz4
    - p7zip
    - python-argcomplete
    - python-defusedxml
    - python-libarchive-c
    - python-magic
    - tar
    - unzip
    - xz
    - zstd
build      : |
    %python3_setup
    make -C doc
install    : |
    %python3_install
    install -Dm00644 debian/zsh-completion/_diffoscope -t $installdir/usr/share/zsh/site-functions/
    install -Dm00644 doc/diffoscope.1 -t $installdir/usr/share/man/man1
