name       : libx11
version    : 1.8.10
release    : 47
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.8.10.tar.gz : b7a1a90d881bb7b94df5cf31509e6b03f15c0972d3ac25ab0441f5fbc789650f
license    : MIT
component  : xorg.library
homepage   : https://www.x.org/
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
emul32     : yes
mancompress: yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static \
               --disable-xf86bigfont
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
