name       : mpvqt
version    : 1.0.1
release    : 2
source     :
    - https://download.kde.org/stable/mpvqt/mpvqt-1.0.1.tar.xz : 9f37b85f319c27f6244743c4259402b0aa2474ed851f0d833d9bd2a0731c178c
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC-BY-SA-4.0
    - CC0-1.0
    - LGPL-2.1-only
    - LGPL-3.0-only
    - LicenseRef-KDE-Accepted-LGPL
    - MIT
component  : multimedia.library
homepage   : https://invent.kde.org/libraries/mpvqt
summary    : MpvQt is a libmpv wrapper for QtQuick2 and QML
description: |
    MpvQt is a libmpv wrapper for QtQuick2 and QML
builddeps  :
    - pkgconfig(Qt6Quick)
    - extra-cmake-modules
    - mpv-libs-devel
rundeps    :
    - devel :
        - mpv-libs-devel
        - qt6-declarative-devel
clang      : yes
optimize   :
    - thin-lto
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
