name       : python-google-api-core
version    : 2.8.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/g/google-api-core/google-api-core-2.8.0.tar.gz : 065bb8e11c605fd232707ae50963dc1c8af5b3c95b4568887515985e6c1156b3
homepage   : https://github.com/googleapis/python-api-core
license    : Apache-2.0
component  : programming.python
summary    : Google API client core library
description: |
    This library is not meant to stand-alone. Instead it defines common helpers used by all Google API clients.
rundeps    :
    - python-google-auth
    - python-googleapis-common-protos
    - python-pytz
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
