name       : python-google-api-core
version    : 2.19.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/g/google-api-core/google-api-core-2.19.0.tar.gz : cf1b7c2694047886d2af1128a03ae99e391108a08804f87cfd35970e49c9cd10
homepage   : https://pypi.org/project/google-api-core/
license    : Apache-2.0
component  : programming.python
summary    : Google API client core library
description: |
    This library is not meant to stand-alone. Instead it defines common helpers used by all Google API clients.
rundeps    :
    - python-google-auth
    - python-googleapis-common-protos
    - python-pytz
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
