name       : gstreamer-1.0
version    : 1.24.6
release    : 55
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.24.6.tar.xz : 64342060d7c6f9e36a35e3be38a4f5ac3b41ed93b0853619be45141ef3cc1b9d
license    : LGPL-2.0-or-later
component  : multimedia.gstreamer
homepage   : https://gstreamer.freedesktop.org/
summary    : Streaming media framework
description: |
    GStreamer is a streaming media framework that enables applications to share a common set of plugins for things like video encoding and decoding, audio encoding and decoding, audio and video filters, audio visualisation, web streaming and anything else that streams in real-time or otherwise. This package only provides base functionality and libraries. You may need at least gst-plugins-base and one of Good, Bad, Ugly or Libav plugins.
emul32     : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig32(libdw)
    - pkgconfig32(libunwind)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsl)
    - rust
clang      : yes
optimize   : thin-lto
setup      : |
    if [[ -n "${EMUL32BUILD}" ]]; then
        CONFIGURE_OPTIONS="-Dintrospection=disabled -Dtests=disabled"
    fi

    %meson_configure -Dpackage-origin="https://getsol.us" \
        -Dexamples=disabled \
        -Dptp-helper-permissions=capabilities \
        -Dwrap_mode=nodownload \
        $CONFIGURE_OPTIONS
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    unset LD_PRELOAD
    %ninja_check
patterns   :
    - 32bit :
        - /usr/share/gdb/auto-load/usr/lib32/
    - devel :
        # Used for running tests in the other gstreamer packages
        - /usr/bin/gst-tester-1.0
