name       : cutter
version    : 2.3.3
release    : 30
source     :
    - https://github.com/rizinorg/cutter/releases/download/v2.3.3/Cutter-v2.3.3-src.tar.gz : 19465855fc7294e64a0302355215891969068bca46dbfdd6d033ad10b3cd1788
homepage   : https://cutter.re/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : A Qt and C++ GUI for rizin reverse engineering framework
description: |
    Cutter is a free and open-source GUI for rizin. Willing to create an advanced, customizable and free reverse engineering framework.
patterns   :
    - devel :
        - /usr/lib64/Cutter/*.cmake
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(libgvc)
    - pkgconfig(python3)
    - pkgconfig(rz_core)
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja \
        -DCUTTER_ENABLE_PYTHON=ON \
        -DCUTTER_USE_ADDITIONAL_RIZIN_PATHS=OFF \
        -DCUTTER_USE_BUNDLED_RIZIN=OFF \
        -DPYTHON_EXECUTABLE=/usr/bin/python3
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 src/re.rizin.cutter.appdata.xml $installdir/usr/share/metainfo/re.rizin.cutter.appdata.xml
