name       : plasma-desktop
version    : 5.92.0
release    : 118
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-desktop-5.92.0.tar.xz : 4df4a24a6acd8962b5377685dfb4dae668a6e4c50a353f6ee84cf4ee1d96e823
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-2.0-only
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE's next generation desktop
description: |
    KDE's next generation desktop.
optimize   : lto
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libevdev)
    - pkgconfig(libcanberra)
    - pkgconfig(phonon4qt6)
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-scanner)
    - pkgconfig(x11)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-image)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-evdev)
    - pkgconfig(xorg-libinput)
    - pkgconfig(xorg-server)
    - pkgconfig(xorg-synaptics)
    - breeze-devel
    - kf6-baloo-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kcmutils-devel
    - kf6-kcodecs-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kded-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kitemmodels-devel
    - kf6-kirigami-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-krunner-devel
    - kf6-ksvg-devel
    - kf6-kwidgetsaddons-devel
    - kf6-kxmlgui-devel
    - kf6-sonnet-devel
    - kscreenlocker-devel
    - kwin-devel
    - libboost-devel
    - libksysguard-devel
    - libplasma-devel
    - plasma5support-devel
    - plasma-activities-devel
    - plasma-activities-stats-devel
    - plasma-workspace-devel
    - qqc2-desktop-style-devel
rundeps    :
    - accountsservice
    - kf6-frameworkintegration
    - kf6-kded
patterns   :
    - /usr/lib64/libkdeinit5*.so
setup      : |
    %apply_patches
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
    rm -rf $installdir/usr/share/doc
