name       : libavif
version    : 1.1.1
release    : 19
source     :
    - https://github.com/AOMediaCodec/libavif/archive/refs/tags/v1.1.1.tar.gz : 914662e16245e062ed73f90112fbb4548241300843a7772d8d441bb6859de45b
license    : BSD-2-Clause
component  : multimedia.library
homepage   : https://github.com/AOMediaCodec/libavif
summary    :
    - Library for encoding and decoding .avif files
    - tools : CLI tools for avif encoding/decoding
description: |
    libavif aims to be a friendly and portable C implementation of the AV1 Image File Format, capable of both encoding and decoding.
builddeps  :
    - pkgconfig(SvtAv1Enc)
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libsharpyuv)
    - pkgconfig(rav1e)
    - libyuv-devel
    - pandoc
checkdeps  :
    - pkgconfig(gtest)
setup      : |
    %cmake_ninja \
                 -DAVIF_BUILD_APPS=ON \
                 -DAVIF_BUILD_MAN_PAGES=ON \
                 -DAVIF_BUILD_TESTS=ON \
                 -DAVIF_CODEC_AOM=SYSTEM \
                 -DAVIF_CODEC_DAV1D=SYSTEM \
                 -DAVIF_CODEC_RAV1E=SYSTEM \
                 -DAVIF_CODEC_SVT=SYSTEM \
                 -DAVIF_GTEST=SYSTEM \
                 -DAVIF_BUILD_GDK_PIXBUF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
patterns   :
    - tools :
        - /usr/bin
        - /usr/share/man
